# Generated by Django 6.0.4 on 2026-04-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontable',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('', 'General'), ('costo_ventas', 'Costo de Ventas'), ('gasto_operativo', 'Gasto Operativo'), ('gasto_financiero', 'Gasto Financiero'), ('otro_ingreso', 'Otro Ingreso'), ('otro_gasto', 'Otro Gasto')], default='', max_length=20, verbose_name='Subcategoría (EE.RR.)'),
        ),
    ]
#a