# Generated by Django 5.2.18 on 2026-10-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cuentacontable_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='observaciones_importacion',
            field=models.TextField(blank=True, default='', verbose_name='Datos pendientes de la importación'),
        ),
    ]
