# Generated by Django 5.2.18 on 2026-10-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_asientocontable_observaciones_importacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='clase',
            field=models.CharField(choices=[('operacion', 'Operación o ajuste'), ('apertura', 'Saldo de apertura'), ('cierre', 'Cierre de resultados')], default='operacion', max_length=12),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='flujo_efectivo',
            field=models.CharField(choices=[('pendiente', 'Pendiente de clasificar'), ('operacion', 'Operación'), ('inversion', 'Inversión'), ('financiacion', 'Financiación')], default='pendiente', max_length=12),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('', 'General'), ('costo_ventas', 'Costo de Ventas'), ('gasto_operativo', 'Gasto Operativo'), ('gasto_financiero', 'Gasto Financiero'), ('otro_ingreso', 'Otro Ingreso'), ('otro_gasto', 'Otro Gasto'), ('impuesto_ganancias', 'Impuesto a las ganancias')], default='', max_length=20, verbose_name='Subcategoría (EE.RR.)'),
        ),
    ]
