# Generated by Django 5.2.18 on 2026-10-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asientocontable_clase_asientocontable_flujo_efectivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='fecha_cierre_ejercicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cierre del ejercicio'),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('', 'General'), ('costo_ventas', 'Costo de Ventas'), ('gasto_operativo', 'Gasto Operativo'), ('gasto_financiero', 'Gasto Financiero'), ('otro_ingreso', 'Otro Ingreso'), ('otro_gasto', 'Otro Gasto'), ('impuesto_ganancias', 'Impuesto a las ganancias'), ('activo_corriente', 'Activo corriente'), ('activo_no_corriente', 'Activo no corriente')], default='', max_length=20, verbose_name='Subcategoría financiera'),
        ),
    ]
