# Generated by Django 5.2.18 on 2026-10-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_asientocontable_fecha_cierre_ejercicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacontable',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('', 'General'), ('costo_ventas', 'Costo de Ventas'), ('gasto_operativo', 'Gasto Operativo'), ('gasto_financiero', 'Gasto Financiero'), ('otro_ingreso', 'Otro Ingreso'), ('otro_gasto', 'Otro Gasto'), ('impuesto_ganancias', 'Impuesto a las ganancias'), ('activo_corriente', 'Activo corriente'), ('activo_no_corriente', 'Activo no corriente'), ('pasivo_corriente', 'Pasivo corriente'), ('pasivo_no_corriente', 'Pasivo no corriente')], default='', max_length=20, verbose_name='Subcategoría financiera'),
        ),
    ]
